# Generated by Django 4.2.15 on 2025-07-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0013_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktype',
            name='colour',
            field=models.CharField(default='#33CC33', max_length=7, verbose_name='Colour'),
        ),
    ]
