# Generated by Django 4.2.15 on 2025-07-09 12:30

from django.db import migrations


def set_color(apps, schema_editor):
    CheckType = apps.get_model('agendas', 'CheckType')
    CheckType.objects.filter(kind='absence').update(colour='#FF0000')


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0014_checktype_colour'),
    ]

    operations = [
        migrations.RunPython(set_color, reverse_code=migrations.RunPython.noop),
    ]
