# Generated by Django 5.2.6 on 2025-09-10 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_lingo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issued_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Émise le'),
        ),
    ]
