# Generated by Django 5.2.6 on 2025-09-10 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='requested_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Demandée le'),
        ),
    ]
