# Generated by Django 1.11.29 on 2020-04-16 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_auth_fc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcaccount',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fcaccount',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
