# Generated by Django 1.11.20 on 2019-06-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_auth_fc', '0003_fcaccount_order1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcaccount',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterUniqueTogether(
            name='fcaccount',
            unique_together={('sub', 'order'), ('user', 'order')},
        ),
    ]
