# Generated by Django 2.2.26 on 2022-06-15 08:02

from django.db import migrations

from authentic2_auth_fc.db import create_fc_authenticator


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_auth_fc', '0006_auto_20220525_1409'),
    ]

    operations = [
        migrations.RunPython(create_fc_authenticator, reverse_code=migrations.RunPython.noop),
    ]
