# Generated by Django 3.2.16 on 2022-11-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_auth_fc', '0007_auto_20220615_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcauthenticator',
            name='link_by_email',
            field=models.BooleanField(
                default=False,
                help_text=(
                    'This legacy behaviour has been deprecated. If unchecked, this checkbox will '
                    "disappear, and linking won't be activable again. If no specific use case on "
                    'the platform requires this option, it is strongly recommended deactivating it '
                    "as, generally speaking, the email address from one's FranceConnect identity "
                    'must not be considered as trustworthy.'
                ),
                verbose_name='Link by email address',
            ),
        ),
    ]
