# Generated by Django 3.2.19 on 2024-08-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_auth_fc', '0008_fcauthenticator_link_by_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcauthenticator',
            name='version',
            field=models.CharField(
                choices=[
                    ('1', 'Version 1 (deprecated mid-2025)'),
                    ('2', 'Version 2 (requires dedicated FC service registration)'),
                ],
                default='2',
                max_length=4,
                verbose_name='Version',
            ),
        ),
    ]
