# Generated by Django 3.2.19 on 2024-08-27 13:38

from django.db import migrations, models

import authentic2.utils.jwc


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_auth_fc', '0009_fcauthenticator_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcauthenticator',
            name='jwkset_json',
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[authentic2.utils.jwc.validate_jwkset],
                verbose_name='JSON WebKey set',
            ),
        ),
    ]
