# Generated by Django 4.2.15 on 2024-12-18 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentic2_auth_fc', '0011_fc_account_discard_nonzero_orders'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fcaccount',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='fcaccount',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='fc_account',
                to=settings.AUTH_USER_MODEL,
                verbose_name='user',
            ),
        ),
        migrations.RemoveField(
            model_name='fcaccount',
            name='order',
        ),
    ]
