# Generated by Django 4.2.15 on 2024-12-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_auth_fc', '0012_alter_fcaccount_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcauthenticator',
            name='supports_multiaccount',
            field=models.BooleanField(
                default=False,
                verbose_name='Supports linking FC identity to several accounts',
                help_text=(
                    'Some use cases require that a unique FranceConnect user identity be linked to '
                    'several user accounts (this option requires adequate FranceConnect mappings and/or '
                    'compatible email-uniqueness settings). Leave unchecked if unsure.'
                ),
            ),
        ),
    ]
