# Generated by Django 2.2.26 on 2022-07-26 15:13

from django.conf import settings
from django.db import migrations
from django.utils import translation
from django.utils.translation import gettext as _


def set_default_button_label(apps, schema_editor):
    SAMLAuthenticator = apps.get_model('authentic2_auth_saml', 'SAMLAuthenticator')
    with translation.override(settings.LANGUAGE_CODE):
        SAMLAuthenticator.objects.update(button_label=_('Login'))


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_auth_saml', '0002_auto_20220608_1559'),
        ('authenticators', '0004_auto_20220726_1708'),
    ]

    operations = [
        migrations.RunPython(set_default_button_label, reverse_code=migrations.RunPython.noop),
    ]
