# Generated by Django 2.2.26 on 2022-08-17 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_auth_saml', '0003_auto_20220726_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samlauthenticator',
            name='login_hints',
        ),
    ]
