# Generated by Django 2.2.26 on 2022-07-28 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_auth_saml', '0006_migrate_jsonfields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samlauthenticator',
            name='a2_attribute_mapping',
        ),
        migrations.RemoveField(
            model_name='samlauthenticator',
            name='lookup_by_attributes',
        ),
    ]
