# Generated by Django 2.2.26 on 2022-09-13 09:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_auth_saml', '0007_remove_jsonfields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setattributeaction',
            old_name='attribute',
            new_name='user_field',
        ),
    ]
