# Generated by Django 2.2.26 on 2022-09-20 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_auth_saml', '0011_alter_authenticator_foreign_key'),
    ]

    database_operations = [migrations.AlterModelTable('AddRoleAction', 'authenticators_addroleaction')]

    state_operations = [migrations.DeleteModel('AddRoleAction')]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations, state_operations=state_operations
        )
    ]
