# Generated by Django 1.11.18 on 2020-03-05 15:45

from django.db import migrations, models

import authentic2.validators


class Migration(migrations.Migration):
    dependencies = [
        ('custom_user', '0016_auto_20180925_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                blank=True,
                max_length=254,
                verbose_name='email address',
                validators=[authentic2.validators.email_validator],
            ),
        ),
    ]
