# Generated by Django 1.11.18 on 2020-03-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('custom_user', '0017_auto_20200305_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_account_deletion_alert',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last account deletion alert'),
        ),
    ]
