# Generated by Django 2.2.12 on 2020-05-05 14:16

from django.db import migrations, models
from django.db.models import JSONField


class Migration(migrations.Migration):
    dependencies = [
        ('custom_user', '0019_add_user_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
                (
                    'id',
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                ('deleted', models.DateTimeField(verbose_name='Deletion date', auto_now_add=True)),
                ('old_uuid', models.TextField(blank=True, null=True, verbose_name='Old UUID')),
                (
                    'old_user_id',
                    models.PositiveIntegerField(blank=True, null=True, verbose_name='Old user id'),
                ),
                (
                    'old_email',
                    models.EmailField(blank=True, max_length=254, null=True, verbose_name='Old email adress'),
                ),
                (
                    'old_data',
                    JSONField(blank=True, null=True, verbose_name='Old data'),
                ),
            ],
            options={
                'verbose_name': 'deleted user',
                'verbose_name_plural': 'deleted users',
                'ordering': ('deleted', 'id'),
            },
        ),
    ]
