# Generated by Django 1.11.29 on 2020-11-02 21:52

from django.contrib.auth.models import AbstractUser
from django.db import migrations


def noop(apps, schema_editor):
    pass


def set_unusable_password(apps, schema_editor):
    User = apps.get_model('custom_user', 'User')
    for user in User.objects.filter(password=''):
        AbstractUser.set_unusable_password(user)
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('custom_user', '0020_deleteduser'),
    ]

    operations = [
        migrations.RunPython(set_unusable_password, noop),
    ]
