# Generated by Django 1.11.29 on 2021-02-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('custom_user', '0024_index_email_by_trigrams'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deactivation datetime'),
        ),
    ]
