# Generated by Django 2.2.23 on 2021-05-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('custom_user', '0026_remove_user_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Deactivation reason'),
        ),
    ]
