# Generated by Django 2.2.24 on 2022-02-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('custom_user', '0030_auto_20220304_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
