# Generated by Django 2.2.26 on 2022-09-19 10:30

from django.db import migrations, models

import authentic2.validators


class Migration(migrations.Migration):
    dependencies = [
        ('custom_user', '0032_index_deleteduser_old_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteduser',
            name='old_phone',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Old phone number'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                validators=[authentic2.validators.PhoneNumberValidator],
                verbose_name='phone number',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified_on',
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name='phone verification date'
            ),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('username__isnull', False),
                    ('email__isnull', False),
                    ('phone__isnull', False),
                    _connector='OR',
                ),
                name='constraint_at_least_one_identifier',
            ),
        ),
    ]
