# Generated by Django 2.2.26 on 2022-09-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('custom_user', '0032_index_deleteduser_old_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteduser',
            name='old_email',
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True, verbose_name='Old email adress'
            ),
        ),
    ]
