# Generated by Django 2.2.26 on 2022-06-08 12:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('custom_user', '0033_user_keepalive'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_sources',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=63),
                default=list,
                size=None,
                null=True,
                blank=True,
                verbose_name='email verification sources',
            ),
        ),
    ]
