# Generated by Django 3.2.18 on 2023-03-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('custom_user', '0034_user_email_verified_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                blank=True, db_index=True, max_length=256, null=True, verbose_name='username'
            ),
        ),
    ]
