# Generated by Django 3.2.18 on 2023-06-28 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('custom_user', '0035_alter_user_username'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='constraint_at_least_one_identifier',
        ),
    ]
