# Generated by Django 2.2.19 on 2021-05-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='api',
            field=models.BooleanField(default=False, verbose_name='API'),
        ),
    ]
