# Generated by Django 1.11.20 on 2020-01-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_idp_oidc', '0011_auto_20180808_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcclient',
            name='access_token_duration',
            field=models.DurationField(
                blank=True,
                default=None,
                null=True,
                verbose_name='time during which the access token is valid',
            ),
        ),
        migrations.AddField(
            model_name='oidcclient',
            name='scope',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Permitted or default scopes (for credentials grant)',
                verbose_name='resource owner credentials grant scope',
            ),
        ),
    ]
