# Generated by Django 2.2.13 on 2020-06-30 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_idp_oidc', '0012_auto_20200122_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidccode',
            name='redirect_uri',
            field=models.TextField(
                validators=[django.core.validators.URLValidator()], verbose_name='redirect URI'
            ),
        ),
    ]
