# Generated by Django 2.2.17 on 2020-11-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_idp_oidc', '0013_auto_20200630_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcaccesstoken',
            name='expired',
            field=models.DateTimeField(null=True, verbose_name='expire'),
        ),
    ]
