# Generated by Django 2.2.24 on 2022-03-04 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('custom_user', '0031_profile_email'),
        ('authentic2_idp_oidc', '0014_auto_20201126_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcauthorization',
            name='profile',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='custom_user.Profile',
                verbose_name='profile',
            ),
        ),
        migrations.AddField(
            model_name='oidcclient',
            name='activate_user_profiles',
            field=models.BooleanField(
                blank=True, default=False, verbose_name="activate users' juridical entity profiles management"
            ),
        ),
        migrations.AddField(
            model_name='oidcclient',
            name='perform_sub_profile_substitution',
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name="make pseudonym subs depend on the user's chosen profile",
            ),
        ),
        migrations.AddField(
            model_name='oidccode',
            name='profile',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='custom_user.Profile',
                verbose_name='user selected profile',
            ),
        ),
    ]
