# Generated by Django 2.2.24 on 2022-03-08 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_idp_oidc', '0015_auto_20220304_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oidcclient',
            name='perform_sub_profile_substitution',
        ),
    ]
