# Generated by Django 2.2.26 on 2022-09-23 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('custom_user', '0031_profile_email'),
        ('authentic2_idp_oidc', '0016_remove_oidcclient_perform_sub_profile_substitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcaccesstoken',
            name='profile',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='custom_user.Profile',
                verbose_name='profile',
            ),
        ),
    ]
