# Generated by Django 3.2.18 on 2023-03-09 13:52

from django.db import migrations, models

import authentic2_idp_oidc.models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_idp_oidc', '0017_oidcaccesstoken_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcaccesstoken',
            name='uuid',
            field=models.CharField(
                db_index=True,
                default=authentic2_idp_oidc.models.generate_uuid,
                max_length=128,
                verbose_name='uuid',
            ),
        ),
    ]
