# Generated by Django 3.2.18 on 2023-10-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_idp_oidc', '0018_alter_oidcaccesstoken_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcclient',
            name='always_save_authorization',
            field=models.BooleanField(
                default=False,
                help_text='do not display the “do not ask again” choice',
                verbose_name='always save authorization',
            ),
        ),
        migrations.AddField(
            model_name='oidcclient',
            name='authorization_default_duration',
            field=models.PositiveIntegerField(
                default=0,
                help_text='0 for default value (one year)',
                verbose_name='duration of saved authorization (in days)',
            ),
        ),
    ]
