# Generated by Django 3.2.23 on 2023-12-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_idp_oidc', '0019_always_save_authorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidccode',
            name='code_challenge',
            field=models.TextField(null=True, verbose_name='Code challenge'),
        ),
        migrations.AddField(
            model_name='oidccode',
            name='code_challenge_method',
            field=models.IntegerField(
                choices=[(1, 'plain'), (2, 'S256')],
                default=1,
                null=True,
                verbose_name='Code challenge method',
            ),
        ),
    ]
