# Generated by Django 3.2.23 on 2023-12-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_idp_oidc', '0020_add_pkce_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcclient',
            name='pkce_code_challenge',
            field=models.BooleanField(
                default=False,
                verbose_name='Client MUST provide a PKCE code_challenge',
                help_text='If PKCE is mandatory, the only method accepted will be S256.',
            ),
        ),
    ]
