# Generated by Django 4.2.15 on 2025-05-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentic2_idp_oidc', '0021_oidcclient_pkce_code_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcclient',
            name='uses_refresh_tokens',
            field=models.BooleanField(
                default=False,
                help_text=(
                    "If activated, a refresh token will be issued in reply to the client's request "
                    'to the the token endpoint (as well as the usual access token). Such refresh '
                    'tokens can then be consumed anytime for access token renewal.'
                ),
                verbose_name='Client is issued a refresh token at token-endpoint request time',
            ),
        ),
    ]
