# Generated by Django 4.2.15 on 2025-08-21 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentic2_idp_oidc', '0023_oidcrefreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidccode',
            name='authorization',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='authentic2_idp_oidc.oidcauthorization',
                verbose_name='authorization',
            ),
        ),
        migrations.AddField(
            model_name='oidcaccesstoken',
            name='authorization',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='authentic2_idp_oidc.oidcauthorization',
                verbose_name='authorization',
            ),
        ),
        migrations.AddField(
            model_name='oidcrefreshtoken',
            name='authorization',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='authentic2_idp_oidc.oidcauthorization',
                verbose_name='authorization',
            ),
        ),
    ]
