# Generated by Django 2.2.26 on 2022-07-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authenticators', '0003_auto_20220413_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseauthenticator',
            name='button_description',
            field=models.CharField(
                blank=True,
                help_text='Description will be shown at the top of login block (unless already set by theme).',
                max_length=256,
                verbose_name='Login block description',
            ),
        ),
        migrations.AddField(
            model_name='baseauthenticator',
            name='button_label',
            field=models.CharField(default='Login', max_length=64, verbose_name='Login button label'),
        ),
    ]
