# Generated by Django 3.2.18 on 2023-06-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authenticators', '0005_addroleaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginpasswordauthenticator',
            name='registration_open',
            field=models.BooleanField(
                default=True, help_text='Allow users to create accounts.', verbose_name='Registration open'
            ),
        ),
    ]
