# Generated by Django 3.2.18 on 2023-06-14 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2', '0048_rename_services_runtime_settings'),
        ('authenticators', '0009_migrate_new_password_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginpasswordauthenticator',
            name='accept_email_authentication',
            field=models.BooleanField(
                default=True, verbose_name='Let the users identify with their email address'
            ),
        ),
        migrations.AddField(
            model_name='loginpasswordauthenticator',
            name='accept_phone_authentication',
            field=models.BooleanField(
                default=False, verbose_name='Let the users identify with their phone number'
            ),
        ),
        migrations.AddField(
            model_name='loginpasswordauthenticator',
            name='phone_identifier_field',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='authentic2.attribute',
                verbose_name='Phone field used as user identifier',
            ),
        ),
    ]
