# Generated by Django 3.2.18 on 2023-06-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authenticators', '0011_migrate_a2_accept_authentication_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginpasswordauthenticator',
            name='min_password_strength',
            field=models.IntegerField(
                default=3,
                blank=True,
                choices=[
                    (None, 'Follow static checks'),
                    (0, 'Very Weak'),
                    (1, 'Weak'),
                    (2, 'Fair'),
                    (3, 'Good'),
                    (4, 'Strong'),
                ],
                null=True,
                verbose_name='Minimum password strength',
                help_text=(
                    'Password strength, using dynamic indicators such as common names, dates and other '
                    'popular patterns. Selecting "static checks" will instead validate that a password '
                    'contains enough different kind of caracters. Password indicator on registration '
                    'form will reflect the chosen policy.'
                ),
            ),
        ),
    ]
