# Generated by Django 3.2.18 on 2023-08-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authenticators', '0013_migrate_min_password_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='addroleaction',
            name='attribute_name',
            field=models.CharField(
                blank=True,
                help_text='Received from identity provider',
                max_length=256,
                verbose_name='Expected attribute name',
            ),
        ),
        migrations.AddField(
            model_name='addroleaction',
            name='attribute_value',
            field=models.CharField(
                blank=True,
                help_text='If missing the role will be removed',
                max_length=256,
                verbose_name='Expected attribute value',
            ),
        ),
    ]
