# Generated by Django 3.2.18 on 2023-08-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authenticators', '0014_auto_20230801_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseauthenticator',
            name='button_label',
            field=models.CharField(default='Login', max_length=256, verbose_name='Login button label'),
        ),
    ]
