# Generated by Django 3.2.18 on 2023-09-27 15:24

from django.db import migrations, models

import authentic2.utils.template


class Migration(migrations.Migration):
    dependencies = [
        ('authenticators', '0015_alter_baseauthenticator_button_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addroleaction',
            name='condition',
            field=models.CharField(
                blank=True,
                default='',
                help_text=(
                    'Django condition controlling role attribution. For example, "\'Admin\' in attributes.groups"'
                    ' will attribute the role if attributes has "groups" attribute containing the value'
                    ' "Admin". Variable "attributes" contains the attributes received from the identity provider. '
                    'If condition is not satisfied the role will be removed.'
                ),
                max_length=1024,
                validators=[authentic2.utils.template.validate_condition_template],
                verbose_name='Condition',
            ),
        ),
    ]
