# Generated by Django 3.2.18 on 2024-04-03 08:36

import django.core.validators
from django.db import migrations, models

import authentic2.apps.authenticators.models


class Migration(migrations.Migration):
    dependencies = [
        ('authenticators', '0019_fix_addroleaction_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginpasswordauthenticator',
            name='sms_code_duration',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text=authentic2.apps.authenticators.models.sms_code_duration_help_text,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        60, 'Ensure that this value is higher than 60, or leave blank for default value.'
                    ),
                    django.core.validators.MaxValueValidator(
                        3600, 'Ensure that this value is lower than 3600, or leave blank for default value.'
                    ),
                ],
                verbose_name='SMS codes lifetime (in seconds)',
            ),
        ),
    ]
