# Generated by Django 3.2.19 on 2024-07-23 15:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authenticators', '0020_loginpasswordauthenticator_sms_code_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginpasswordauthenticator',
            name='registration_forbidden_email_domains',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128),
                blank=True,
                default=list,
                help_text='Comma separated list of domains (example : "@gmail.com, @outlook.fr")',
                size=None,
                verbose_name='Email domains forbidden for registration',
            ),
        ),
    ]
