# Generated by Django 4.2.15 on 2025-05-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'authenticators',
            '0021_loginpasswordauthenticator_registration_forbidden_email_domains',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='baseauthenticator',
            name='allow_user_change_email',
            field=models.BooleanField(default=True, verbose_name='Allow user change email'),
        ),
    ]
