# Generated by Django 4.2.15 on 2025-06-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticators', '0022_baseauthenticator_allow_user_change_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseauthenticator',
            name='button_image',
            field=models.ImageField(
                blank=True,
                help_text='When an image is set, login button label must contain a text to describe it, to guarantee correct website accessibility.',
                upload_to='authenticators/button_images',
                verbose_name='Login button image',
            ),
        ),
    ]
