# Generated by Django 2.2.26 on 2022-09-21 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regie',
            fields=[
                (
                    'id',
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                ('label', models.CharField(max_length=150, verbose_name='Label')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Identifier')),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        help_text='Optional regie description.',
                        null=True,
                        verbose_name='Description',
                    ),
                ),
                (
                    'cashier_role',
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='auth.Group',
                        verbose_name='Cashier Role',
                    ),
                ),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
