# Generated by Django 2.2.26 on 2022-12-01 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoicing', '0003_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                (
                    'id',
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                ('date_start', models.DateField(verbose_name='Start date')),
                ('date_end', models.DateField(verbose_name='End date')),
                ('date_issue', models.DateField(verbose_name='Issue date')),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                (
                    'id',
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                ('draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'campaign',
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoicing.Campaign'),
                ),
            ],
        ),
        migrations.AddField(
            model_name='draftinvoice',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoicing.Pool'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draftinvoiceline',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoicing.Pool'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoicing.Pool'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoicing.Pool'),
            preserve_default=False,
        ),
    ]
