# Generated by Django 3.2.18 on 2023-03-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoicing', '0019_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='label',
            field=models.CharField(default='Campaign', max_length=150, verbose_name='Label'),
            preserve_default=False,
        ),
    ]
