# Generated by Django 3.2.25 on 2024-08-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoicing', '0096_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditline',
            name='slug',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='draftinvoiceline',
            name='slug',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='draftjournalline',
            name='slug',
            field=models.SlugField(max_length=500),
        ),
        migrations.AlterField(
            model_name='injectedline',
            name='slug',
            field=models.SlugField(max_length=500),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='slug',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='slug',
            field=models.SlugField(max_length=500),
        ),
    ]
