# Generated by Django 3.2.25 on 2024-08-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoicing', '0097_increase_line_slug_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditline',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='draftinvoiceline',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
