# Generated by Django 3.2.25 on 2024-08-27 06:30

from django.db import migrations, models

import lingo.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ('invoicing', '0098_increase_line_description_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='regie',
            name='custom_address',
            field=lingo.utils.fields.RichTextField(blank=True, null=True, verbose_name='Custom Address'),
        ),
        migrations.AddField(
            model_name='regie',
            name='custom_invoice_extra_info',
            field=lingo.utils.fields.RichTextField(
                blank=True,
                help_text='Displayed below the address block.',
                null=True,
                verbose_name='Custom invoice extra information',
            ),
        ),
        migrations.AddField(
            model_name='regie',
            name='custom_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Custom Logo'),
        ),
    ]
