# Generated by Django 3.2.25 on 2024-09-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoicing', '0102_fix_line_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditline',
            name='slug',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='draftinvoiceline',
            name='slug',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='draftjournalline',
            name='slug',
            field=models.SlugField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='injectedline',
            name='slug',
            field=models.SlugField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='slug',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='slug',
            field=models.SlugField(max_length=1000),
        ),
    ]
