# Generated by Django 3.2.19 on 2024-09-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoicing', '0103_increase_line_slug_length_to_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditline',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='creditline',
            name='label',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='draftinvoiceline',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='draftinvoiceline',
            name='label',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='draftjournalline',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='draftjournalline',
            name='label',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='injectedline',
            name='label',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='label',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='label',
            field=models.TextField(),
        ),
    ]
