# Generated by Django 3.2.16 on 2023-10-29 15:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('epayment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                (
                    'id',
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ('start_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('bank_data', models.JSONField(blank=True, default=dict)),
                ('order_id', models.CharField(max_length=200)),
                ('bank_transaction_id', models.CharField(max_length=200, null=True)),
                ('bank_transaction_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('next_url', models.TextField(null=True)),
                (
                    'backend',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to='epayment.paymentbackend'
                    ),
                ),
            ],
        ),
    ]
