# Generated by Django 3.2.16 on 2023-12-18 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoicing', '0074_credit'),
        ('epayment', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbackend',
            name='regie',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.regie'
            ),
        ),
    ]
