# Generated by Django 3.2.16 on 2023-11-18 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoicing', '0074_credit'),
        ('epayment', '0003_paymentbackend_regie'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to='invoicing.invoice'
            ),
        ),
    ]
