# Generated by Django 4.2.18 on 2025-08-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0013_multi_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketlineitem',
            name='subject',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
