# Generated by Django 2.2.12 on 2020-04-28 01:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('saml', '0017_auto_20170710_1738'),
    ]

    operations = [
        migrations.RunSQL('TRUNCATE saml_keyvalue', migrations.RunSQL.noop, elidable=True),
    ]
