# Generated by Django 2.2.13 on 2020-06-21 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('saml', '0018_truncate_saml_keyvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libertyprovider',
            name='ca_cert_chain',
        ),
        migrations.RemoveField(
            model_name='libertyprovider',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='libertyprovider',
            name='ssl_certificate',
        ),
    ]
