# Generated by Django 3.2.18 on 2023-03-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('saml', '0019_auto_20200621_1558'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='libertysession',
            index=models.Index(
                fields=['provider_id', 'django_session_key'], name='saml_libert_provide_39bb6c_idx'
            ),
        ),
    ]
