# Generated by Django 1.11.18 on 2019-03-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('a2_rbac', '0018_organizationalunit_user_add_password_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalunit',
            name='show_username',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show username'),
        ),
    ]
