# Generated by Django 1.11.18 on 2020-03-17 14:14

from django.db import migrations, models

import authentic2.a2_rbac.utils


class Migration(migrations.Migration):
    dependencies = [
        ('a2_rbac', '0020_partial_unique_index_on_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalunit',
            name='uuid',
            field=models.CharField(
                default=authentic2.a2_rbac.utils.get_hex_uuid, max_length=32, unique=True, verbose_name='uuid'
            ),
        ),
        migrations.AlterField(
            model_name='role',
            name='uuid',
            field=models.CharField(
                default=authentic2.a2_rbac.utils.get_hex_uuid, max_length=32, unique=True, verbose_name='uuid'
            ),
        ),
    ]
