# Generated by Django 1.11.18 on 2020-04-02 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('a2_rbac', '0021_auto_20200317_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalunit',
            name='clean_unused_accounts_alert',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                default=730,
                validators=[
                    django.core.validators.MinValueValidator(
                        30, 'Ensure that this value is greater than 30 days, or leave blank for deactivating.'
                    )
                ],
                verbose_name='Days after which the user receives an account deletion alert',
            ),
        ),
        migrations.AddField(
            model_name='organizationalunit',
            name='clean_unused_accounts_deletion',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                default=760,
                validators=[
                    django.core.validators.MinValueValidator(
                        30, 'Ensure that this value is greater than 30 days, or leave blank for deactivating.'
                    )
                ],
                verbose_name='Delay in days before cleaning unused accounts',
            ),
        ),
    ]
