# Generated by Django 1.11.18 on 2020-05-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('a2_rbac', '0022_auto_20200402_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_members',
            field=models.BooleanField(default=True, verbose_name='Allow adding or deleting role members'),
        ),
    ]
