# Generated by Django 2.2.19 on 2021-06-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('a2_rbac', '0024_fix_self_admin_perm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalunit',
            name='user_can_reset_password',
            field=models.BooleanField(
                choices=[(None, 'System default'), (True, 'Yes'), (False, 'No')],
                verbose_name='Users can reset password',
                default=None,
                blank=True,
                null=True,
            ),
        ),
    ]
