# Generated by Django 2.2.19 on 2021-12-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('a2_rbac', '0025_auto_20210622_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalunit',
            name='check_required_on_login_attributes',
            field=models.BooleanField(
                blank=True, default=True, verbose_name='Check required on login attributes'
            ),
        ),
    ]
