# Generated by Django 2.2.19 on 2021-12-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('a2_rbac', '0026_organizationalunit_check_required_on_login_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
    ]
