# Generated by Django 2.2.24 on 2022-01-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('a2_rbac', '0027_auto_20211213_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalunit',
            name='home_url',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='Home URL'),
        ),
    ]
