# Generated by Django 2.2.26 on 2022-09-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('a2_rbac', '0029_use_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalunit',
            name='min_password_strength',
            field=models.IntegerField(
                blank=True,
                choices=[
                    (None, 'System default'),
                    (0, 'Very Weak'),
                    (1, 'Weak'),
                    (2, 'Fair'),
                    (3, 'Good'),
                    (4, 'Strong'),
                ],
                default=None,
                null=True,
                verbose_name='Minimum password strength',
            ),
        ),
    ]
