# Generated by Django 2.2.26 on 2022-10-11 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('a2_rbac', '0030_organizationalunit_min_password_strength'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                (
                    'id',
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                ('slug', models.CharField(max_length=32, unique=True, verbose_name='slug')),
            ],
        ),
        migrations.AddField(
            model_name='permission',
            name='operation_new',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='a2_rbac.Operation',
                verbose_name='operation',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permission',
            name='operation',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='django_rbac.Operation',
                verbose_name='operation',
                null=True,
            ),
        ),
        migrations.RemoveConstraint(
            model_name='permission',
            name='null_ou_uniq_idx',
        ),
    ]
