# Generated by Django 2.2.26 on 2022-10-25 09:35

import django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('a2_rbac', '0033_remove_old_operation_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='details',
            field=models.TextField(blank=True, verbose_name='Role details (frontoffice)'),
        ),
        migrations.AddField(
            model_name='role',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name='role',
            name='emails_to_members',
            field=models.BooleanField(default=True, verbose_name='Emails to members'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
