# Generated by Django 2.2.26 on 2022-10-25 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('a2_rbac', '0035_populate_role_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleAttribute',
        ),
    ]
