# Generated by Django 3.2.18 on 2023-06-20 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('a2_rbac', '0036_delete_roleattribute'),
        ('authenticators', '0013_migrate_min_password_strength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalunit',
            name='min_password_strength',
        ),
    ]
