# Generated by Django 3.2.18 on 2023-11-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('a2_rbac', '0037_remove_organizationalunit_min_password_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalunit',
            name='phone_is_unique',
            field=models.BooleanField(blank=True, default=False, verbose_name='Phone is unique'),
        ),
    ]
