# Generated by Django 3.2.23 on 2024-03-28 16:50

import django.contrib.postgres.indexes
import django.db.models.expressions
import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('a2_rbac', '0039_set_user_view_permissions_by_ou'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='role',
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper(
                        django.db.models.expressions.Func(
                            django.db.models.expressions.F('name'), function='public.immutable_unaccent'
                        )
                    ),
                    'public.gin_trgm_ops',
                ),
                name='name_idx',
            ),
        ),
    ]
