# Generated by Django 4.2.18 on 2025-02-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a2_rbac', '0041_update_role_administration_permissions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='roleparenting',
            new_name='a2_rbac_rol_child_i_1908e7_idx',
            old_fields=('child', 'parent', 'direct'),
        ),
    ]
