# Generated by Django 1.11.18 on 2020-03-17 16:32

from django.db import migrations, models

import authentic2.utils.template


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_auth_oidc', '0006_oidcprovider_claims_parameter_supported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcclaimmapping',
            name='claim',
            field=models.CharField(
                max_length=128, verbose_name='claim', validators=[authentic2.utils.template.validate_template]
            ),
        ),
    ]
