# Generated by Django 2.2.28 on 2022-04-13 14:22

import django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_auth_oidc', '0008_auto_20201102_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcprovider',
            name='baseauthenticator_ptr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oidcaccount',
            name='provider',
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='accounts',
                to='authentic2_auth_oidc.OIDCProvider',
                verbose_name='provider',
            ),
        ),
        migrations.AlterField(
            model_name='oidcclaimmapping',
            name='provider',
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='claim_mappings',
                to='authentic2_auth_oidc.OIDCProvider',
                verbose_name='provider',
            ),
        ),
    ]
