# Generated by Django 2.2.28 on 2022-05-24 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_auth_oidc', '0011_auto_20220413_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcaccount',
            name='provider',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='accounts',
                to='authentic2_auth_oidc.OIDCProvider',
                verbose_name='provider',
            ),
        ),
        migrations.AlterField(
            model_name='oidcclaimmapping',
            name='provider',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='claim_mappings',
                to='authentic2_auth_oidc.OIDCProvider',
                verbose_name='provider',
            ),
        ),
    ]
