# Generated by Django 2.2.26 on 2022-07-26 15:14

from django.db import migrations
from django.db.models import F


def set_default_button_label(apps, schema_editor):
    OIDCProvider = apps.get_model('authentic2_auth_oidc', 'OIDCProvider')
    OIDCProvider.objects.update(button_label=F('name'))


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_auth_oidc', '0012_auto_20220524_1147'),
        ('authenticators', '0004_auto_20220726_1708'),
    ]

    operations = [
        migrations.RunPython(set_default_button_label, reverse_code=migrations.RunPython.noop),
    ]
