# Generated by Django 2.2.26 on 2022-08-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_auth_oidc', '0016_auto_20221019_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcprovider',
            name='a2_synchronization_supported',
            field=models.BooleanField(default=False, verbose_name='Authentic2 synchronization supported'),
        ),
        migrations.AddField(
            model_name='oidcprovider',
            name='last_sync_time',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Last synchronization time', editable=False
            ),
        ),
    ]
