# Generated by Django 2.2.26 on 2023-01-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_auth_oidc', '0013_synchronization_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcprovider',
            name='passive_authn_supported',
            field=models.BooleanField(default=True, verbose_name='Supports passive authentication'),
        ),
    ]
