# Generated by Django 2.2.26 on 2022-09-20 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_auth_oidc', '0013_auto_20220726_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oidcclaimmapping',
            old_name='provider',
            new_name='authenticator',
        ),
    ]
