# Generated by Django 2.2.26 on 2022-10-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_auth_oidc', '0015_auto_20220922_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcprovider',
            name='issuer',
            field=models.CharField(db_index=True, max_length=256, verbose_name='issuer'),
        ),
        migrations.AddConstraint(
            model_name='oidcprovider',
            constraint=models.UniqueConstraint(
                condition=models.Q(_negated=True, issuer=''),
                fields=('issuer',),
                name='unique_issuer_if_not_empty',
            ),
        ),
    ]
