# Generated by Django 3.2.18 on 2023-11-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2_auth_oidc', '0014_oidcprovider_passive_authn_supported'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcprovider',
            name='jwkset_url',
            field=models.URLField(
                blank=True,
                help_text='This URL is usually part of the “well-known” URLs as per the OIDC specifications',
                max_length=256,
                default='',
                verbose_name="URL of the provider's JSON WebKey Set",
            ),
        ),
    ]
