# Generated by Django 2.2.17 on 2020-12-04 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('django_rbac', '0005_auto_20171209_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='name',
        ),
    ]
