# Generated by Django 2.2.23 on 2022-01-31 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_rbac', '0006_remove_operation_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('operation', 'ou', 'target_ct', 'target_id')},
        ),
        migrations.AlterUniqueTogether(
            name='roleparenting',
            unique_together={('parent', 'child', 'direct')},
        ),
        migrations.AlterIndexTogether(
            name='roleparenting',
            index_together={('child', 'parent', 'direct')},
        ),
    ]
