# Generated by Django 2.2.19 on 2021-10-06 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_rbac', '0007_add_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleparenting',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roleparenting',
            name='deleted',
            field=models.DateTimeField(null=True, verbose_name='Deletion date'),
        ),
    ]
