# Generated by Django 2.2.26 on 2022-10-04 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('django_rbac', '0008_add_roleparenting_soft_delete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationalUnit',
        ),
        migrations.RemoveField(
            model_name='role',
            name='members',
        ),
        migrations.RemoveField(
            model_name='role',
            name='ou',
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AlterUniqueTogether(
            name='roleparenting',
            unique_together=None,
        ),
        migrations.AlterIndexTogether(
            name='roleparenting',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='roleparenting',
            name='child',
        ),
        migrations.RemoveField(
            model_name='roleparenting',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='RoleParenting',
        ),
    ]
