# Generated by Django 2.2.26 on 2022-10-11 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('django_rbac', '0009_auto_20221004_1343'),
        ('a2_rbac', '0033_remove_old_operation_fk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
