# Generated by Django 1.11.20 on 2019-06-17 09:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('custom_user', '0016_auto_20180925_1107'),
        ('authentic2', '0023_auto_20181031_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPUser',
            fields=[],
            options={
                'proxy': True,
            },
            bases=('custom_user.user',),
        ),
        migrations.AlterUniqueTogether(
            name='userexternalid',
            unique_together={('source', 'external_id')},
        ),
    ]
