# Generated by Django 1.11.20 on 2019-10-09 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2', '0024_auto_20190617_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteduser',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='deletion',
                to=settings.AUTH_USER_MODEL,
                verbose_name='user',
            ),
        ),
    ]
