# Generated by Django 1.11.20 on 2020-02-11 10:27

import uuid

from django.db import migrations, models
from django.db.models import JSONField


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2', '0025_auto_20191009_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                (
                    'uuid',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='Identifier',
                    ),
                ),
                ('kind', models.CharField(max_length=32, verbose_name='Kind')),
                (
                    'content',
                    JSONField(blank=True, verbose_name='Content'),
                ),
                ('created', models.DateTimeField(verbose_name='Creation date', auto_now_add=True)),
                ('expires', models.DateTimeField(verbose_name='Expires')),
            ],
            options={
                'ordering': ('-expires', 'kind', 'uuid'),
            },
        ),
    ]
