# Generated by Django 1.11.18 on 2020-10-13 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2', '0028_trigram_unaccent_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributevalue',
            options={
                'ordering': ('attribute__order', 'id'),
                'verbose_name': 'attribute value',
                'verbose_name_plural': 'attribute values',
            },
        ),
    ]
