# Generated by Django 2.2.17 on 2021-01-16 14:22

from django.contrib.postgres.search import SearchVector
from django.db import migrations


def initialize_search_vector(apps, schema_editor):
    AttributeValue = apps.get_model('authentic2', 'AttributeValue')
    AttributeValue.all_objects.update(search_vector=SearchVector('content'))


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2', '0031_add_search_vector_to_attributes'),
    ]

    operations = [
        migrations.RunPython(initialize_search_vector, reverse_code=migrations.RunPython.noop),
    ]
