# Generated by Django 2.2.17 on 2021-01-25 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2', '0032_initialize_search_vectors'),
    ]

    operations = []
