# Generated by Django 2.2.19 on 2021-07-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2', '0033_recreate_immutable_unaccent'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='required_on_login',
            field=models.BooleanField(blank=True, default=False, verbose_name='required on login'),
        ),
    ]
