# Generated by Django 2.2.27 on 2022-03-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('custom_user', '0030_auto_20220304_1136'),
        ('authentic2', '0035_service_home_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='profile_types',
            field=models.ManyToManyField(
                blank=True,
                related_name='services+',
                through='custom_user.ServiceProfileType',
                to='custom_user.ProfileType',
                verbose_name='allowed services for this profile type',
            ),
        ),
    ]
