# Generated by Django 2.2.24 on 2022-03-31 13:13

from django.db import migrations, models

import authentic2.validators


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2', '0036_service_profile_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='colour',
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                validators=[authentic2.validators.HexaColourValidator()],
                verbose_name='Colour',
            ),
        ),
        migrations.AddField(
            model_name='service',
            name='logo',
            field=models.ImageField(blank=True, upload_to='services/logos', verbose_name='Logo'),
        ),
    ]
