# Generated by Django 2.2.27 on 2022-04-07 15:20

from django.db import migrations, models

from authentic2.migrations import DropPartialIndexes


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2', '0038_make_service_ou_non_null'),
    ]

    operations = [
        DropPartialIndexes(
            'AttributeValue',
            'authentic2_attributevalue',
            'authentic2_attribute_value_partial_unique_idx',
            (),
            ('content_type_id', 'object_id', 'attribute_id'),
            where=(('multiple = %s', (False,)),),
        ),
        migrations.AddConstraint(
            model_name='attributevalue',
            constraint=models.UniqueConstraint(
                condition=models.Q(multiple=False),
                fields=('content_type', 'object_id', 'attribute'),
                name='unique_attribute_idx',
            ),
        ),
    ]
