# Generated by Django 2.2.27 on 2022-04-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2', '0040_add_external_guid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('name', models.TextField(primary_key=True, serialize=False, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Lock',
                'verbose_name_plural': 'Lock',
            },
        ),
    ]
