# Generated by Django 2.2.26 on 2022-07-07 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.RBAC_ROLE_MODEL),
        ('authentic2', '0041_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIClient',
            fields=[
                (
                    'id',
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('identifier', models.CharField(max_length=256, verbose_name='Identifier')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                (
                    'restrict_to_anonymised_data',
                    models.BooleanField(default=False, verbose_name='Restrict to anonymised data'),
                ),
                (
                    'apiclient_roles',
                    models.ManyToManyField(
                        blank=True,
                        related_name='apiclients',
                        to=settings.RBAC_ROLE_MODEL,
                        verbose_name='roles',
                    ),
                ),
            ],
            options={
                'verbose_name': 'APIClient',
                'verbose_name_plural': 'APIClient',
            },
        ),
    ]
