# Generated by Django 2.2.26 on 2022-09-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2', '0042_api_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiclient',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
