# Generated by Django 2.2.26 on 2022-05-30 12:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2', '0043_api_client_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='last_verified_on',
            field=models.DateTimeField(null=True, verbose_name='last verification timestamp'),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='verification_sources',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=63),
                null=True,
                size=None,
                verbose_name='verification sources',
                blank=True,
            ),
        ),
    ]
