# Generated by Django 2.2.26 on 2022-11-17 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import authentic2.a2_rbac.utils


class Migration(migrations.Migration):
    dependencies = [
        ('a2_rbac', '0036_delete_roleattribute'),
        ('authentic2', '0045_smscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiclient',
            name='ou',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.RBAC_OU_MODEL,
                verbose_name='organizational unit',
                default=authentic2.a2_rbac.utils.get_default_ou_pk,
            ),
        ),
    ]
