# Generated by Django 2.2.26 on 2022-12-22 09:13

import django.db.models.deletion
from django.db import migrations, models

import authentic2.a2_rbac.utils


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2', '0044_apiclient_ou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiclient',
            name='ou',
            field=models.ForeignKey(
                blank=True,
                default=authentic2.a2_rbac.utils.get_default_ou_pk,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='a2_rbac.OrganizationalUnit',
                verbose_name='organizational unit',
            ),
        ),
    ]
