# Generated by Django 2.2.26 on 2023-01-17 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentic2', '0047_initialize_services_runtime_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscode',
            name='fake',
            field=models.BooleanField(default=False, verbose_name='Is a fake code'),
        ),
        migrations.AddField(
            model_name='smscode',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='user',
            ),
        ),
    ]
