# Generated by Django 3.2.18 on 2023-04-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2', '0045_auto_20221222_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                (
                    'id',
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                ('key', models.CharField(max_length=128, unique=True, verbose_name='key')),
                ('value', models.JSONField(blank=True, verbose_name='value')),
            ],
        ),
    ]
