# Generated by Django 3.2.18 on 2023-08-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2', '0048_rename_services_runtime_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiclient',
            name='allowed_user_attributes',
            field=models.ManyToManyField(
                blank=True,
                related_name='apiclients',
                to='authentic2.Attribute',
                verbose_name='allowed user attributes',
            ),
        ),
    ]
