# Generated by Django 3.2.19 on 2024-05-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2', '0051_hash_existing_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiclient',
            name='allowed_ip',
            field=models.TextField(blank=True, verbose_name='IP allowed'),
        ),
        migrations.AddField(
            model_name='apiclient',
            name='denied_ip',
            field=models.TextField(blank=True, verbose_name='IP denied'),
        ),
        migrations.AddField(
            model_name='apiclient',
            name='ip_allow_deny',
            field=models.BooleanField(default=False, verbose_name='IP restriction order allow/deny'),
        ),
    ]
