# Generated by Django 4.2.15 on 2024-12-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2', '0055_remove_duplicate_user_imports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimport',
            name='uuid',
            field=models.CharField(max_length=128, unique=True, verbose_name='uuid'),
        ),
    ]
