# Generated by Django 4.2.15 on 2024-12-11 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('authentic2', '0056_alter_userimport_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='verification_sources',
        ),
    ]
